spring:
  profiles:
    active:
      - prod
  data:
    redis:
      host: my-redis
      port: 6379

  session:
    store-type: redis
#    redis:
#      host: my-redis
#      port: 6379
#      password:

logging:
  level:
    org:
      springframework:
        data:
          redis: DEBUG