
spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/study-project
#    username: root
#    password: my-secret-pw
    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    username: root
    password: 1234


  jpa:
    hibernate:
      ddl-auto: none