spring:
  datasource:
    # sist docker mysql
    url: jdbc:mysql://127.0.0.1:3307/spring-test-db
    username: root
    password: 1234

#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@127.0.0.1:1521:xe
#      username: root
#      password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop

